womenCorpus<-scan(file.choose(), what="", sep="\n")
womenCorpus<-gsub("--\\s.*", "", womenCorpus)
womenCorpus<-gsub("([-'])|[[:punct:]]", "", womenCorpus)
womenCorpus<-strsplit(womenCorpus, "[[:space:]]+")
womenCorpus<-data.frame(unlist(womenCorpus))
womenCorpus<-Corpus(VectorSource(womenCorpus$unlist.womenCorpus.))
womenCorpus<-tm_map(womenCorpus, PlainTextDocument)
womenCorpus<-tm_map(womenCorpus, removePunctuation)
womenCorpus<-tm_map(womenCorpus, stemDocument)

menCorpus<-scan(file.choose(), what="", sep="\n")
menCorpus<-gsub("--\\s.*", "", menCorpus)
menCorpus<-gsub("([-'])|[[:punct:]]", "", menCorpus)
menCorpus<-strsplit(menCorpus, "[[:space:]]+")
menCorpus<-data.frame(unlist(menCorpus))
menCorpus<-Corpus(VectorSource(menCorpus$unlist.menCorpus.))
menCorpus<-tm_map(menCorpus, PlainTextDocument)
menCorpus<-tm_map(menCorpus, removePunctuation)
menCorpus<-tm_map(menCorpus, stemDocument)
